name: CI

on:
  push:
    branches: [ "[0-9]+.[0-9]+" ]
    paths-ignore: [ "README.md", "CHANGELOG.md" ]
  pull_request:
    branches: [ "[0-9]+.[0-9]+" ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Composer install
        uses: ramsey/composer-install@v2

      - name: Run PHPStan
        if: success() || failure()
        run: composer exec -- phpstan analyse --memory-limit=512M --ansi --no-progress --level=max src tests --error-format=checkstyle > phpstan-checkstyle.xml

      - name: Report PHPStan
        if: success() || failure()
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          name: PHPStan
          path: phpstan-checkstyle.xml

      - name: Run PHPCodeSniffer
        if: success() || failure()
        run: composer exec -- phpcs --colors --report=checkstyle --report-checkstyle=phpcs-checkstyle.xml

      - uses: jwgmeligmeyling/checkstyle-github-action@master
        if: success() || failure()
        with:
          name: PHPCodeSniffer
          path: phpcs-checkstyle.xml

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ "8.3", "8.4" ]
        dependency-versions: [ lowest, highest ]
        include:
          - php: "8.1"
            dependency-versions: highest
          - php: "8.2"
            dependency-versions: highest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Composer install
        uses: ramsey/composer-install@v2

      - name: Generate tz data
        run: make tz

      - name: Run PHPUnit
        if: success() || failure()
        run: composer exec -- phpunit --testsuite tests --colors=always --log-junit=phpunit-${{ matrix.php }}-${{ matrix.dependency-versions }}.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure()
        with:
          check_name: "PHPUnit (${{ matrix.php }} ${{ matrix.dependency-versions }} deps)"
          junit_files: "phpunit-*.xml"
